# Generated by Django 5.0.7 on 2025-05-26 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Signalement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image_url", models.URLField(blank=True, null=True)),
                ("location", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("voirie", "Voirie (nids-de-poule, routes abîmées)"),
                            ("infrastructure", "Infrastructure publique"),
                            ("eclairage", "Éclairage public"),
                            ("ordures", "Gestion des ordures"),
                            ("eau", "Problèmes d'eau"),
                            ("assainissement", "Assainissement"),
                            ("pollution", "Pollution"),
                            ("espaces_verts", "Espaces verts"),
                            ("securite", "Sécurité publique"),
                            ("signalisation", "Signalisation"),
                            ("transport", "Transports publics"),
                            ("animaux_errants", "Animaux errants"),
                            ("urbanisme", "Urbanisme"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours"),
                            ("resolu", "Résolu"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signalements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
