# Generated by Django 5.2.1 on 2025-08-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signalement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signalement",
            name="status",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("en_cours", "En cours"),
                    ("resolu", "Résolu"),
                    ("rejected", "Rejeté"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
